# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multiSigma <- function(signal, deg = 3L) {
    .Call(`_mwaved_multiSigma`, signal, deg)
}

waveletThresh <- function(beta, thr, shrinkType = "hard", j0 = 3L, deg = 3L) {
    .Call(`_mwaved_waveletThresh`, beta, thr, shrinkType, j0, deg)
}

multiProj <- function(beta, j0 = 3L, j1 = NA_integer_, deg = 3L) {
    .Call(`_mwaved_multiProj`, beta, j0, j1, deg)
}

multiThresh <- function(signal, G, alpha = as.numeric( c()), resolution = "smooth", j0 = 3L, j1 = NA_integer_, eta = NA_real_, deg = 3L) {
    .Call(`_mwaved_multiThresh`, signal, G, alpha, resolution, j0, j1, eta, deg)
}

multiEstimate <- function(signal, G, alpha = as.numeric( c()), resolution = "smooth", blur = "direct", sigma = as.numeric( c()), j0 = 3L, j1 = NA_integer_, eta = NA_real_, thresh = as.numeric( c()), shrinkType = "hard", deg = 3L) {
    .Call(`_mwaved_multiEstimate`, signal, G, alpha, resolution, blur, sigma, j0, j1, eta, thresh, shrinkType, deg)
}

multiCoef <- function(signal, G, alpha = as.numeric( c()), j0 = 3L, j1 = NA_integer_, deg = 3L) {
    .Call(`_mwaved_multiCoef`, signal, G, alpha, j0, j1, deg)
}

multiWaveD <- function(signal, G, alpha = as.numeric( c()), resolution = "smooth", blur = "direct", j0 = 3L, j1 = NA_integer_, eta = NA_real_, thresh = as.numeric( c()), shrinkType = "hard", deg = 3L) {
    .Call(`_mwaved_multiWaveD`, signal, G, alpha, resolution, blur, j0, j1, eta, thresh, shrinkType, deg)
}

directDetect <- function(x) {
    .Call(`_mwaved_directDetect`, x)
}

boxcarDetect <- function(x) {
    .Call(`_mwaved_boxcarDetect`, x)
}

directBlur <- function(n, m) {
    .Call(`_mwaved_directBlur`, n, m)
}

theoreticalEta <- function(alpha, blur, g_fft, sigma) {
    .Call(`_mwaved_theoreticalEta`, alpha, blur, g_fft, sigma)
}

