# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multiSigma <- function(signal, deg = 3L) {
    .Call('mwaved_multiSigma', PACKAGE = 'mwaved', signal, deg)
}

waveletThresh <- function(betaList, thr, shrinkType = "hard") {
    .Call('mwaved_waveletThresh', PACKAGE = 'mwaved', betaList, thr, shrinkType)
}

multiProj <- function(beta, j0 = 3L, j1 = NA_integer_, deg = 3L) {
    .Call('mwaved_multiProj', PACKAGE = 'mwaved', beta, j0, j1, deg)
}

multiThresh <- function(signal, G, alpha = as.numeric( c()), blur = "direct", j0 = 3L, j1 = NA_integer_, eta = NA_real_, deg = 3L) {
    .Call('mwaved_multiThresh', PACKAGE = 'mwaved', signal, G, alpha, blur, j0, j1, eta, deg)
}

multiEstimate <- function(signal, G, alpha = as.numeric( c()), blur = "direct", sigma = as.numeric( c()), j0 = 3L, j1 = NA_integer_, eta = NA_real_, thresh = as.numeric( c()), shrinkage = "Hard", deg = 3L) {
    .Call('mwaved_multiEstimate', PACKAGE = 'mwaved', signal, G, alpha, blur, sigma, j0, j1, eta, thresh, shrinkage, deg)
}

multiCoef <- function(signal, G, alpha = as.numeric( c()), blur = "direct", j0 = 3L, j1 = NA_integer_, thresh = as.numeric( c()), eta = NA_real_, deg = 3L) {
    .Call('mwaved_multiCoef', PACKAGE = 'mwaved', signal, G, alpha, blur, j0, j1, thresh, eta, deg)
}

multiWaveD <- function(signal, G, alpha = as.numeric( c()), j0 = 3L, j1 = NA_integer_, blur = "direct", thresh = as.numeric( c()), eta = NA_real_, shrinkage = "Hard", deg = 3L) {
    .Call('mwaved_multiWaveD', PACKAGE = 'mwaved', signal, G, alpha, j0, j1, blur, thresh, eta, shrinkage, deg)
}

